### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by ZhiyangZhou24** [facebookresearch/NGDF#1]
Cannot clone repository, I have some ploblem when clone the repository. 
`Cloning into '/home/user/NGDF/OMG-Planner'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by thomasweng15** [comment]
Thanks for filing an issue. Another user was able to clone the repository without this issue. This documentation from Github may be helpful for your error: https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#should-the-sudo-command-be-used-with-git. Let me know if you are still unable to clone after troubleshooting.
