### ISSUE TITLE
obs from bullet not correct

### ISSUE THREAD

**Issue by KJZhuAutomatic** [facebookresearch/NGDF#14]
Hi, thanks for the nice work.
I deploy the code successfully, but when run `bash scripts/eval/reach_and_gr
asp/perobj.sh`,  the saved video which names {object}_{scene}.avi is null, after debug i find:
### image size not match
the size defined in `omg_bullet.panda_scene.init_video_writer` is (640, 480) (width, height), but the bullet render image `obs["rgb"]` in `omg_bullet.utils.bullet_execute_plan` has shape (640, 480, 3), the mismatch size make the saved video is null. I am confused why other follower not report the bug, tell me what's wrong please.

**Comment by KJZhuAutomatic** [comment]
OK, got it, the shape mismatch from `omg_bullet.envs.acronym_env`. In my codebase, the returns of  `rgba, zbuffer, mask = p.getCameraImage`  are all one-dim vector not in (height, width, ...), so I reshape it. After correct I can get video and gifs right.

**Comment by ChristianMilianti** [comment]
Hi @KJZhuAutomatic,

I think I have a similar error, could you share the code you changed to fix the error?

Thanks! :)

**Comment by KJZhuAutomatic** [comment]
hi, after the code `rgba, zbuffer, mask = p.getCameraImage`, i reshape it using '
zbuffer = np.array(zbuffer).reshape(self._window_height, self._window_width)
            rgba = np.array(rgba).reshape(self._window_height, self._window_width, 4)
            mask = np.array(mask).reshape(self._window_height, self._window_width)', hope work for you.

**Comment by KJZhuAutomatic** [comment]
@ChristianMilianti  hi, after the code` rgba, zbuffer, mask = p.getCameraImage`, i reshape it using 
```
zbuffer = np.array(zbuffer).reshape(self._window_height, self._window_width)
rgba = np.array(rgba).reshape(self._window_height, self._window_width, 4)
mask = np.array(mask).reshape(self._window_height, self._window_width)
```, 
hope work for you.

**Comment by ChristianMilianti** [comment]
Thanks @KJZhuAutomatic , that seems to have fixed the issue!
